# common configuration

server:
  port: 8081

gg:
  jte:
    developmentMode: false
    usePrecompiledTemplates: true
    templateSuffix: .kte

# 'checkout' domain configuration

checkout:
  product-feed-url: http://host.docker.internal:8080/product/api/v1/feed


# 'account' domain configuration

account:
  base-url: http://localhost:3000