# common configuration

server:
  port: 8080

gg:
  jte:
    developmentMode: false
    usePrecompiledTemplates: true
    templateSuffix: .kte


# 'discovery' domain configuration

# 'product' domain configuration

# 'navigation' domain configuration